export const navLinks = [
  {
    id: 1,
    name: 'Home',
    url: '/',
  },
  {
    id: 2,
    name: 'About',
    url: '/#about',
  },
  {
    id: 3,
    name: 'Portfolio',
    url: '/portfolio',
  },
  {
    id: 4,
    name: 'Contact',
    url: '/#contact',
  },
];

export const featuredProjects = [
  {
    title: 'Revival Stream',
    description: 'A site for streaming godly music',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/revival-stream.png',
    liveLink: 'https://revivalstream.co/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-2',
  },
  {
    title: 'Kompletecare Healthcare Platform',
    description: 'Healthcare management platform with seamless user experience',
    tech: ['Nuxt.js', 'Bootstrap', 'Graphql'],
    image: '/projects/kompletecare.png',
    liveLink: 'https://kompletecare.com/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-1',
  },
  {
    title: 'Delta7',
    description: 'A website for NFTs',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/delta7.png',
    liveLink: 'https://delta7.netlify.app',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'MC Holly',
    description: 'A Site for comedy Reservation',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    image: '/projects/mc-holly.png',
    liveLink: 'https://www.mcholly.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  // {
  //   title: 'CypherCrescent',
  //   description:
  //     'A Business Website where people buy courses and learn about the company',
  //   tech: ['ReactJS', 'Bootstrap'],
  //   image: '/projects/cyphercrescent.png',
  //   liveLink: 'https://cyphercrescentlearning.com/',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-2',
  // },
  // {
  //   title: 'Fhenix',
  //   description: 'A training company website',
  //   tech: ['VueJS', 'Bootstrap'],
  //   image: '/projects/fhenix.png',
  //   liveLink: 'https://fhenix-test.vercel.app/',
  //   codeLink: '#',
  //   size: 'col-span-1',
  // },
];
export const featuredProjects11 = [
  {
    title: 'Weather Wiz',
    description: 'A website for getting current weather information',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/weather.png',
    liveLink: 'https://weather-wiz-delta.vercel.app/',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Shopsy',
    description: 'An Ecommerce Website mimicking a real shopping platform',
    tech: ['VueJS', 'Tailwind CSS', 'Vuex'],
    image: '/projects/shopsy.png',
    liveLink: 'https://shoppie-psi.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Car Showcase',
    description: 'A website for car display',
    tech: ['NextJS', 'Tailwind'],
    image: '/projects/car-showcase.png',
    liveLink: 'https://car-showcase-next-ojhe.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  {
    title: 'Developer portfolio',
    description:
      'A developer portfolio that combines multiple skills and creativity',
    tech: ['VueJS', 'Bootstrap'],
    image: '/projects/portfolio.png',
    liveLink: 'https://silver-lining.netlify.app',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Nft Display',
    description: 'A website for Nft display',
    tech: ['React.js', 'Tailwind CSS'],
    image: '/projects/nft.png',
    liveLink: 'https://nft-chip.vercel.app/',
    codeLink: '#',
    size: 'col-span-1',
  },
  // {
  //   title: 'CypherCrescent',
  //   description:
  //     'A Business Website where people buy courses and learn about the company',
  //   tech: ['ReactJS', 'Bootstrap'],
  //   image: '/projects/cyphercrescent.png',
  //   liveLink: 'https://cyphercrescentlearning.com/',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-2',
  // },
  // {
  //   title: 'Fhenix',
  //   description: 'A training company website',
  //   tech: ['VueJS', 'Bootstrap'],
  //   image: '/projects/fhenix.png',
  //   liveLink: 'https://fhenix-test.vercel.app/',
  //   codeLink: '#',
  //   size: 'col-span-1',
  // },
];
export const featuredProjects12 = [
  {
    title: 'Revival Stream',
    description: 'A site for streaming godly music',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/revival-stream.png',
    liveLink: 'https://revivalstream.co/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-2',
  },
  {
    title: 'Kompletecare Healthcare Platform',
    description: 'Healthcare management platform with seamless user experience',
    tech: ['Nuxt.js', 'Bootstrap', 'Graphql'],
    image: '/projects/kompletecare.png',
    liveLink: 'https://kompletecare.com/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-1',
  },
  {
    title: 'Delta7',
    description: 'A website for NFTs',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/delta7.png',
    liveLink: 'https://delta7.netlify.app',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'MC Holly',
    description: 'A Site for comedy Reservation',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    image: '/projects/mc-holly.png',
    liveLink: 'https://www.mcholly.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  // {
  //   title: 'CypherCrescent',
  //   description:
  //     'A Business Website where people buy courses and learn about the company',
  //   tech: ['ReactJS', 'Bootstrap'],
  //   image: '/projects/cyphercrescent.png',
  //   liveLink: 'https://cyphercrescentlearning.com/',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-2',
  // },
  // {
  //   title: 'Fhenix',
  //   description: 'A training company website',
  //   tech: ['VueJS', 'Bootstrap'],
  //   image: '/projects/fhenix.png',
  //   liveLink: 'https://fhenix-test.vercel.app/',
  //   codeLink: '#',
  //   size: 'col-span-1',
  // },
];

export const featuredProjects0 = [
  {
    title: 'Revival Stream',
    description: 'A site for streaming godly music',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/revival-stream.png',
    liveLink: 'https://revivalstream.co/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-2',
  },
  {
    title: 'Kompletecare Healthcare Platform',
    description: 'Healthcare management platform with seamless user experience',
    tech: ['Nuxt.js', 'Bootstrap', 'Graphql'],
    image: '/projects/kompletecare.png',
    liveLink: 'https://kompletecare.com/',
    codeLink: '#',
    size: 'col-span-1 lg:row-span-1',
  },
  // {
  //   title: 'Delta7',
  //   description: 'A website for NFTs',
  //   tech: ['ReactJS', 'Bootstrap'],
  //   image: '/projects/delta7.png',
  //   liveLink: 'https://delta7.netlify.app',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-2',
  // },
  // {
  //   title: 'MC Holly',
  //   description: 'A Site for comedy Reservation',
  //   tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
  //   image: '/projects/mc-holly.png',
  //   liveLink: 'https://www.mcholly.com/',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-1',
  // },
  // {
  //   title: 'CypherCrescent',
  //   description:
  //     'A Business Website where people buy courses and learn about the company',
  //   tech: ['ReactJS', 'Bootstrap'],
  //   image: '/projects/cyphercrescent.png',
  //   liveLink: 'https://cyphercrescentlearning.com/',
  //   codeLink: '#',
  //   size: 'col-span-1 row-span-2',
  // },
  // {
  //   title: 'Fhenix',
  //   description: 'A training company website',
  //   tech: ['VueJS', 'Bootstrap'],
  //   image: '/projects/fhenix.png',
  //   liveLink: 'https://fhenix-test.vercel.app/',
  //   codeLink: '#',
  //   size: 'col-span-1',
  // },
];
export const featuredProjects1 = [
  {
    title: 'Delta7',
    description: 'A website for NFTs',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/delta7.png',
    liveLink: 'https://delta7.netlify.app',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'MC Holly',
    description: 'A Site for comedy Reservation',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    image: '/projects/mc-holly.png',
    liveLink: 'https://www.mcholly.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
];
export const featuredProjects2 = [
  {
    title: 'CypherCrescent',
    description:
      'A Business Website where people buy courses and learn about the company',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/cyphercrescent.png',
    liveLink: 'https://cyphercrescentlearning.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Fhenix',
    description: 'A training company website',
    tech: ['VueJS', 'Bootstrap'],
    image: '/projects/fhenix.png',
    liveLink: 'https://fhenix-test.vercel.app/',
    codeLink: '#',
    size: 'col-span-1',
  },
];

export const projects = [
  {
    title: 'Revival Stream',
    description: 'A site for streaming godly music',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/revival-stream.png',
    liveLink: 'https://revivalstream.co/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Kompletecare Healthcare Platform',
    description: 'Healthcare management platform with seamless user experience',
    tech: ['Nuxt.js', 'Bootstrap', 'Graphql'],
    image: '/projects/kompletecare.png',
    liveLink: 'https://kompletecare.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  {
    title: 'Delta7',
    description: 'A website for NFTs',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/delta7.png',
    liveLink: 'https://delta7.netlify.app',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'MC Holly',
    description: 'A Site for comedy Reservation',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    image: '/projects/mc-holly.png',
    liveLink: 'https://www.mcholly.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  {
    title: 'CypherCrescent',
    description:
      'A Business Website where people buy courses and learn about the company',
    tech: ['ReactJS', 'Bootstrap'],
    image: '/projects/cyphercrescent.png',
    liveLink: 'https://cyphercrescentlearning.com/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Fhenix',
    description: 'A training company website',
    tech: ['VueJS', 'Bootstrap'],
    image: '/projects/fhenix.png',
    liveLink: 'https://fhenix-test.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-1',
  },
  {
    title: 'Weather Wiz',
    description: 'A website for getting current weather information',
    tech: ['Next.js', 'TypeScript', 'Tailwind CSS', 'REST API'],
    image: '/projects/weather.png',
    liveLink: 'https://weather-wiz-delta.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Shopsy',
    description: 'An Ecommerce Website mimicking a real shopping platform',
    tech: ['VueJS', 'Tailwind CSS', 'Vuex'],
    image: '/projects/shopsy.png',
    liveLink: 'https://shoppie-psi.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Car Showcase',
    description: 'A website for car display',
    tech: ['NextJS', 'Tailwind'],
    image: '/projects/car-showcase.png',
    liveLink: 'https://car-showcase-next-ojhe.vercel.app/',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Nft Display',
    description: 'A website for Nft display',
    tech: ['React.js', 'Tailwind CSS'],
    image: '/projects/nft.png',
    liveLink: 'https://nft-chip.vercel.app/',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Nuxt moovie',
    description: 'A website for fetching movies and watching previews',
    tech: ['NuxtJs', 'Tailwind'],
    image: '/projects/movie.png',
    liveLink: 'https://nuxt3-movie-app.vercel.app/',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Developer portfolio',
    description:
      'A developer portfolio that combines multiple skills and creativity',
    tech: ['VueJS', 'Bootstrap'],
    image: '/projects/portfolio.png',
    liveLink: 'https://silver-lining.netlify.app',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Unsplash Gallery',
    description: 'A test project to build a gallery',
    tech: ['VueJS', 'Bootstrap'],
    image: '/projects/unsplash-gallery-vue.png',
    liveLink: 'https://unsplash-gallery-test.netlify.app',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Untitled UI Dashboard',
    description: 'A test project to build a dashboard',
    tech: ['NuxtJS', 'Bootstrap'],
    image: '/projects/untitled-ui-nuxt.png',
    liveLink: 'https://untitled-ui-nuxt.netlify.app',
    codeLink: '#',
    size: 'col-span-1 row-span-2',
  },
  {
    title: 'Country Search Challenge',
    description: 'An application to display countries and search for them',
    tech: ['HTML', 'CSS', 'JavaScript'],
    image: '/projects/country-search-challenge.png',
    liveLink: 'https://country-search-challenge.netlify.app',
    codeLink: '#',
    size: 'col-span-1',
  },
  {
    title: 'Pexel Clone',
    description: 'A clone of Pexels, where users can search for images',
    tech: ['NuxtJS', 'Tailwind CSS'],
    image: '/projects/pexels-clone-tesst.png',
    liveLink: 'https://pexels-clone-test.netlify.app',
    codeLink: '#',
    size: 'col-span-1',
  },
];

export const thingsIDo = [
  {
    id: 1,
    name: 'Web Develoment',
    description:
      'Need a websit for your company to boost your reputation while creating awareness? How about developing that web project you have in mind?',
    icon: '',
  },
];

export const testimonials = [
  {
    id: 1,
    message:
      'I highly recommend Ogochukwu for any web development project. He are highly skilled, professional, and always willing to go the extra mile to ensure that the project is completed on time',
    name: 'Bisi',
    role: 'Product Manager',
    image: '',
  },
  {
    id: 2,
    message:
      "I was impressed with Ogochukwu's attention to detail and commitment to quality. They were able to quickly identify and fix any issues, and their code was clean and well-organized.",
    name: 'Mr John',
    role: 'Manager',
    image: '',
  },
  {
    id: 3,
    message:
      'Working with Ogochukwu and the other developers was a pleasure. They were highly communicative throughout the project, and always kept us informed of their progress. The end result was a beautiful and functional website that met all of our requirements.',
    name: 'Tofunmi',
    role: 'Manager',
    image: '',
  },
  {
    id: 4,
    message:
      'I would highly recommend Ogochukwu to anyone looking for a reliable and skilled web developer. They are passionate about their work and always deliver top-notch results',
    name: 'Aaron',
    role: 'Manager',
    image: '',
  },
  {
    id: 5,
    message:
      'I have worked with Ogochukwu on multiple projects, and they have consistently delivered high-quality work. They are always willing to listen to feedback and make changes as needed to ensure that the project meets our expectations.',
    name: 'Chilo',
    role: 'Manager',
    image: '',
  },
  {
    id: 6,
    message:
      'Learning web development was sort of difficult for me but my story changed when I met Ogochuks as a mentor in an Internship. He explains things to the bare minimum',
    name: 'Chidiogo',
    role: 'Frontend trainee',
    image: '',
  },
];
